### PR TITLE
add hostAlias section to data loader

### PR DESCRIPTION
**Pull request by gchickma**
Add hostAlias section to data loader

### CODE REVIEW

**Comment by tlawrie** [comment]
This is probably a Flow 3.8.0 change as it's not been verified in all the Flow 3.7.0 changes so far.

**Comment by gchickma** [comment]
Change is very minor, i.e. it includes an optional hostAlias block to the loader pod descriptor.
Have tested it in other charts similar to Flow and works as expected.
If it can be merged in I am happy to test as part of 3.7.0.

**Comment by tlawrie** [comment]
My preference is that it waits until 3.8.0 as 3.7.0 has been in draft release for 2 weeks awaiting on one front end tag. However, we now have multiple chart and worker tags that are trying to be added with creep in the release scope.

However, if it was agreed in the community meeting, then we can add but we would need the documentation updated ASAP and README updated.

**Comment by tlawrie** [comment]
Also has it been tested 
- new install without host alias
- new install with host alias
- upgrade to an install without host alias
- upgrade to an install with host alias

The TLS change required two last-minute emergency fixes in release shakeout so im trying to make sure that we don't ship with a faulty install.

**Comment by gchickma** [comment]
There's no documentation currently for hostAliases in the README.md
I will add a new section

**Comment by gchickma** [comment]
Wrt testing, yes to all for similar chart, no to Flow as it hasn't been merged and packaged as yet

**Comment by gchickma** [comment]
Updated chart pushed

**Review by tlawrie — APPROVED** [review]

**Review by morarucostel — APPROVED** [review]

**Comment by timrbula** [comment]
@gchickma With the two approvals, lets merge this in?

**Pull request merged**
