### PR TITLE
Support for k8s 122 (networking.k8s.io/v1 ingress API)

### PR DESCRIPTION
**Pull request by liviu-niculescu**
Closes #

n/a

#### Changelog

**New**

- Add _helpers.tpl to auto determine supported ingress class

**Changed**

- default value for values.global.ingress.pathType
- ingress templates

**Removed**

n/a

#### Testing / Reviewing

this can be verified by installing the chart on different k8s versions - <1.14, <1.19 and after

---

implemented originally by @aiciobanu for ess-core

### CODE REVIEW

**Review by gchickma — CHANGES_REQUESTED** [review]
@liviu-niculescu changes look good, you just need to increment the **_version_** on bmrg-bosun/Chart.yaml

**Comment by tlawrie** [comment]
Hi @gchickma @liviu-niculescu some good helpers... similar to what we did in Flow chart manually

```
{{- $apiV1 := false -}}
{{- $apiVersion := "extensions/v1beta1" -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- $apiVersion = "networking.k8s.io/v1" -}}
{{- $apiV1 = true -}}
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
{{- $apiVersion = "networking.k8s.io/v1beta1" -}}
{{- end }}
{{- range $k, $v := $values.apps }}
apiVersion: {{ $apiVersion }}
```

Biggest difference is Flow was checking APIVersions instead of KubeVersion. Not sure if you want to do the same.

Alternatively, I would suggest not bothering with backwards compatability. We have removed this from the v4 of Flow as Kubernetes 1.22 is already EOL. 

image

**Comment by liviu-niculescu** [comment]
> Hi @gchickma @liviu-niculescu some good helpers... similar to what we did in Flow chart manually
> 
> ```
> {{- $apiV1 := false -}}
> {{- $apiVersion := "extensions/v1beta1" -}}
> {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
> {{- $apiVersion = "networking.k8s.io/v1" -}}
> {{- $apiV1 = true -}}
> {{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
> {{- $apiVersion = "networking.k8s.io/v1beta1" -}}
> {{- end }}
> {{- range $k, $v := $values.apps }}
> apiVersion: {{ $apiVersion }}
> ```
> 
> Biggest difference is Flow was checking APIVersions instead of KubeVersion. Not sure if you want to do the same.
> 
> Alternatively, I would **highly encourage** not bothering with backwards compatibility in this case - **Kubernetes 1.22 is already EOL**. We have removed this from the v4 of Flow.
> 
> image

makes sense, was thinking that if people want to use say latest cicd chart for some other changes but are still running on older versions (as some still do), it would be a benefit

we could hardcode the API version though I suppose

thoughts @tlawrie @gchickma ?

**Comment by gchickma** [comment]
@liviu-niculescu I agree with still support older versions of K8S, can't hurt, and as we know there are a lot of older K8S clusters still running across the broader teams we support.

Also, Boomerang CICD will not be upgraded anytime soon to use Flow v4.

With respect to checking K8S version vs API version - the API version method seems cleaner given it appears you do not need specify/check actual K8S versions per se, i.e., there's a helper method to use for checking which capability exists.

**Comment by liviu-niculescu** [comment]
alright guys I changed it up similar to Flow and tested in a k8s 1.23 environment
have a look pls and let me know if you have any comment

cc @gchickma @tlawrie

**Review by gchickma — APPROVED** [review]
Looks good thx @liviu-niculescu

**Comment by tlawrie** [comment]
Approving based on IBMs request.

**Review by tlawrie — APPROVED** [review]

**Pull request merged**
