### PR TITLE
Add missing required values for NATS Jetstream

### PR DESCRIPTION
**Pull request by corcoja**
Add missing required values for NATS Jetstream.

#### Changelog

**New**

- New values in `values.yaml`.

**Changed**

- Updated `configmap` to use new values from `values.yaml`.

### CODE REVIEW

**Review by gchickma — APPROVED** [review]

**Comment by tlawrie** [comment]
I've reverted this PR whilst @morarucostel @corcoja and myself discuss the need for these parameters.

My understanding was that the following values are needed in the application.properties of the services to be passed to the Lib. But are not needed to be configurable by the end user.

```
    eventing.jetstream.stream.name={{ $values.jetstream.stream.name }}
    eventing.jetstream.stream.subject={{ $values.jetstream.stream.subject }}
    eventing.jetstream.consumer.push.name={{ $values.jetstream.consumer.pushBasedName }}
    eventing.jetstream.consumer.push.delivery-subject={{ $values.jetstream.consumer.pushBasedDeliverySubject }}
    eventing.jetstream.consumer.pull.name={{ $values.jetstream.consumer.pullBasedName }}
```

**Comment by morarucostel** [comment]
Hey, I believe that as long as both components (the stream and consumer) that are publishing and consuming the events are part the flow, there is no necessity to expose that configuration in the helm values. 

My suggestion here is to prefix the name of the stream and consumer to the release name to allow an user to have multiple flow instances running on the same NATS instance, if they want to do that. 

So, I would remove the configuration from the helm values and handle it internally in the app configuration.

**Comment by corcoja** [comment]
@tlawrie

> My understanding was that the following values are needed in the application.properties of the services to be passed to the Lib

You're right, these properties are required by the services that have `flow.lib.streaming` integrated, in our case `flow.service.listener` and `flow.service.workflow`.

The reason I decided to add these properties to chart's `values.yaml` file is that we don't package NATS Jetstream with Flow app, thus it is up to the end user to configure one if he decides to use it. If the end user already has an instance of NATS, he might want to control the configuration of `Streams` and `Consumers` (name, subjects, properties, etc.) that are being used by Flow to avoid any interference with other apps (if any).

As per @morarucostel's suggestion, I will create a new PR with hardcoded values in `configmap.yaml` but with `.Release.Name` as the base for these properties.

See PR #46

**Comment by tlawrie** [comment]
Hi @corcoja @morarucostel thanks for the discussion. To clarify though do we even want this change in the configmap or can it just be in the application.properties of the services?

>  If the end user already has an instance of NATS, he might want to control the configuration of Streams and Consumers (name, subjects, properties, etc.) that are being used by Flow to avoid any interference with other apps (if any).

Based on the above, I think this PR then makes sense.

**Pull request merged**
